### ISSUE TITLE
'ProjectionModule' was not found in './core/index'

### ISSUE THREAD

**Issue by CoDrie** [danielzen/material-todo#2]
Hello Mr. Zen,

i justed cloned your repo and got this error.
```
WARNING in ./~/@angular/material/module.js
64:4 export 'ProjectionModule' was not found in './core/index'

WARNING in ./~/@angular/material/module.js
89:16 export 'ProjectionModule' was not found in './core/index'

WARNING in ./~/@angular/material/dialog/index.js
21:75 export 'Platform' was not found in '../core'
```
Any idea how i can solve this?

**Comment by danielzen** [comment]
You can try setting "@angular/material": "2.0.0-alpha.9", in package.json (Removing the '^' currently there)

This should force the version of Material Design to the one I used when I did the demo....

**Comment by CoDrie** [comment]
Working! This was just the problem.
